apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pulumi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  target:
    name: pulumi 
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: pulumi  # name