apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: uriah-app
spec:
  stack: uriah-app
  destroyOnFinalize: true
  backend: s3://pulumi-argo
  projectRepo: https://github.com/ahrakos/pulumi-argo
  branch: refs/heads/main
  gitAuth:
    accessToken:
      type: Secret
      secret:
        name: pulumi
        key: GITHUB_TOKEN
  config:
    'aws:region': us-east-2
