apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: dev1
spec:
  stack: dev1
  destroyOnFinalize: true
  backend: s3://pulumi-argo
  projectRepo: https://github.com/ahrakos/pulumi-argo
  repoDir: ./environments/dev1
  branch: refs/heads/main
  gitAuth:
    accessToken:
      type: Secret
      secret:
        name: pulumi
        key: GITHUB_TOKEN
  config:
    'aws:region': us-east-2
