apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: dev2
spec:
  stack: dev2
  destroyOnFinalize: true
  backend: s3://pulumi-argo
  projectRepo: https://github.com/ahrakos/pulumi-argo
  repoDir: /projects/psr
  branch: refs/heads/main
  gitAuth:
    accessToken:
      type: Secret
      secret:
        name: pulumi
        key: GITHUB_TOKEN
  config:
    'aws:region': us-east-2
    envName: dev2
